Disable remove_bg due to bug
When remove_bg=True the following error occurs
```
AttributeError: 'numpy.ndarray' object has no attribute 'numpy'
```
at
https://github.com/XuzheZ/PTNet3D/blob/63b0560714ff1157e3493ed63c2bf591a1c8c218/data/data_util.py#L61

In CloudInfant the scan object is wrapped in torch.from_numpy that
may have fixed the issue:
https://github.com/InfantBrainAI/CloudInfant/blob/6545cefa0311109a092ba9add97edd41ca758d74/src/code/data/data_util.py#L68